### ISSUE TITLE
Proot Warning, Can't Sanitize Bindings

### ISSUE THREAD

**Issue by Yonko12345678** [23xvx/Termux-Proot-Custom-Installer#1]
~/ubuntu-in-termux $ ./startubuntu.sh
proot warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs, cwd = /, $PATH=(null))

How do I fix this?

**Comment by 23xvx** [comment]
Sorry, do you mean ubuntu-in-termux ? 
This repository is about custom proot installer , which is not the same .
Also, I am not the person who contribute that repository 
If you have issue, you can go to 
https://github.com/MFDGaming/ubuntu-in-termux

**Comment by Yonko12345678** [comment]
I resolved this problem, but I have another question.. is:
can I use Termux X11 with Termux-Proot-Custom, I want to use  Termux X11 as VNC server.

in XFCE4 desktop, Termux X11 work fine by using: 
export DISPLAY=:0
dbus-launch --exit-with-session startxfce4 &

I tried 
export DISPLAY=:0
dbus-launch --exit-with-session gnome-session &

but doesn't work...

**Comment by 23xvx** [comment]
Gnome-session requires systemd , which doesn't work in proot linux.
However, gnome shell works fine since it doesn't require systemd.
Therefore , you can start gnome desktop with 

export DISPLAY=:0
dbus-launch --exit-with-session gnome-shell --x11 &
